### ISSUE TITLE
Since the last update to v5. Adding URL often doesn't work.

### ISSUE THREAD

**Issue by mrtpcet** [wallabag/ios-app#258] opened 2020-03-11 22:03 UTC
|  iPhone 6s
| iOS 13.3.1
| App Version : 5.0.0
| Wallabag server version: 2.3.8

Since the last update to v5. Adding URL often doesn't work.

As soon as I want to share a url to the wallabag application, the icon appears on the screen but does not go away. 
I have to copy the address, open the application and add it manually. 
However, it doesn't work. The sync wheel. I have to force restart app: sometimes my url has been saved and sometimes not.

**Comment by bourvill** [comment] 2020-03-12 08:15
I have the impression that there are problems with the authentication of your application.

Are you self-hosted?

**Comment by mrtpcet** [comment] 2020-03-12 11:58
Yes I am, an installation with Yunohost.

**Comment by bourvill** [comment] 2020-03-19 08:49
Hello, on your instance? Can you create an account for me on your instance?

**Comment by mrtpcet** [comment] 2020-03-19 09:05
> Hello, on your instance? Can you create an account for me on your instance?

Hello. Of course. Here you user id: https://privatebin.net/?91c758c5e3d7e4b9#GsgxAzQ5k6ev6kxg7T3eXvjSkGXxFJFuTuhJfo34cFpE (the note is destroyed after the first reading)

**Comment by bourvill** [comment] 2020-03-19 10:13
I can't reproduce your problem.
I'm using your instance.
The workflow of adding from the app is not finished, completed. I will work on it so that the addition to the list is immediate without having to redo a synchronization.

When you try to add a URL, do you have a good internet connection?

Sorry for all these stupid questions, but I really don't have a clue to reproduce the problem

**Comment by mrtpcet** [comment] 2020-03-22 00:07
> When you try to add a URL, do you have a good internet connection?
Yes, my very good Home connexion. 

Honestly, since the past day, the bug is pretty less present. Two times, when I past directly an url in the app, I was forced to kill the app and reopen it. 
I don’t really understand ..
Maybe my mobile vpn ? (Proton vpn) or my dns ad guard ? (Privacy Pro).

**Comment by bourvill** [comment] 2020-04-12 16:31
Error is fixed with 5.0.1?

**Comment by mrtpcet** [comment] 2020-04-12 16:44
Regularly (1 time out of 3), when I share a link to wallabag from an application, the wallabag logo appears and stays frozen on the screen (it doesn't disappear like when it works).  I have to drag the logo down and start sharing again: it usually works the second time.

**Comment by bourvill** [comment] 2020-04-13 22:00
I seem to be a connection problem. When the problem occur do you have good connection?

**Comment by mrtpcet** [comment] 2020-04-15 08:50
These last few weeks I am at home with a very fast fiber connection (300mb/300mb) in wifi 5Ghz.
Nevertheless, I use protonVPN as VPN and Privacy Pro as DNS server intermediary.
I will try today to disable them to see.

**Comment by mrtpcet** [comment] 2020-04-15 09:24
Okay, I tried two things:
1. Disable protonVPN
Test the share
2. Disable Proton VPN and PrivacyPro
Test the share

Results: the problem appeared after about ten shares. Then, it appears regularly every 2-3 shares. Sometimes, I have to drag the logo twice and try again before the sharing works.

**Comment by bourvill** [comment] 2020-04-29 08:40
hello @mrtpcet the latest beta version incorporates a new communication mechanism with the server.
Could you take a test?

**Comment by mrtpcet** [comment] 2020-04-29 09:25
Okay, here we go !

**Comment by mrtpcet** [comment] 2020-05-07 21:54
I've had no problems since the last two builds (264 and 263) ;-)

**Comment by bourvill** [comment] 2020-05-10 08:50
Ok, fix is merged and app is in review by apple :)

I close this Issue :)

**Comment by haltdev** [comment] 2020-05-15 17:59
Was this issue to have been fixed in 5.0.2? Because I still have the problem. When using the “share” option from Safari (or Firefox) and pressing on Wallabag, an overlay is displayed with Wallabag logo, but nothing else, and it just freezes there. I have to swipe it down to close it and the article I wanted to save is indeed not saved. 

If I open the iOS app, my Wallabag articles are all shown and synced, so the app itself appears to be working and not a login/authentication issue.

**Comment by bourvill** [comment] 2020-05-15 18:16
Can your share your url ?
If you try to add url manually from app? Do you have an error ?

**Comment by haltdev** [comment] 2020-05-15 18:28
It happens with any URL. Here is a specific one:
https://ashadeofteal.com/rustic-diy-bookshelf-with-ikea-ekby-brackets/

Adding the URL directly in the app via “add entry” does the something similar - it says “submitting” then goes back to “submit” button after a few seconds, and the URL is still in the field. After submittal within the app I would expect the URL to be cleared and a message to say something like “added!”

Also via the Share extension within other apps (Safari) I would expect “Added!” To be shown and the wallabag icon logo to clear by itself. 

It would also be good if we could add a tag to the article during both processes - via “Share” and via “add entry” in the app.

**Comment by bourvill** [comment] 2020-05-15 20:39
Do you have any issue with sync ?

**Comment by haltdev** [comment] 2020-05-16 17:41
No issue with sync.

**Comment by bourvill** [comment] 2020-05-18 07:48
@haltdev When you try to add url with share extension, can you check your web server instance? Article is added?

If you have access to your webserver log, can you check log access when your try to add url ?

**Comment by bourvill** [comment] 2020-06-17 07:56
Do you still have the problem since the last update?

**Closed** 2020-08-31 09:24 UTC
Labels: Bug, Needs more information
