### ISSUE TITLE
Add a font size selector or a theme with a bigger font

### ISSUE THREAD

**Issue by raphaelfournier** [wallabag/ios-app#127] opened 2017-11-22 22:21 UTC
My iOS system font size is bigger than for most users. The default font size in Wallabag app is too small for long reads, and does not seem modifiable. Would it be possible to add a font size selector (or just a theme with a bigger font)?

**Comment by bourvill** [comment] 2017-11-23 10:22
good idea! we can add for a next update a font size selector

**Comment by thibaultamartin** [comment] 2020-02-21 08:31
Closing this issue as a duplicate of #173

**Closed by thibaultamartin** 2020-02-21 08:31 UTC
