### ISSUE TITLE
Trying to view a saved Youtube video on iPhone locks the app

### ISSUE THREAD

**Issue by z720** [wallabag/ios-app#205] opened 2019-08-01 08:54 UTC
| Q             | A
| ------------- | ---
| Device?       | iPhone Xr
| Device Os version    | 12.3.1
| App Version   | 4.1.2
| Wallabag server version | Framabag 2.2.3

### Steps to reproduce/test case

1. Add a Youtube video to Framabag (either on the web interface or using the iPhone share from safari or tweetbot)
2. Open wallabg app on iPhone
3. Try to open the saved page
4. The article opens (the title is visible)
5. Within less than a second a blank panel slides up 
6. Application is "locked" by the panel with no action visible to close the panel.

See video: https://www.dropbox.com/s/pabch2cckbfu1iv/IMG_2882.TRIM.MOV?dl=0

**Comment by bourvill** [comment] 2019-08-01 09:45
strange bug. Thanks for your feedback. I'm looking soon

**Comment by thibaultamartin** [comment] 2020-02-21 08:09
Hello ,

The Wallabag app is being rewritten. I cannot reproduce it in the build 242 of Wallabag 5.0.0 Beta, meaning your issue is most likely fixed in the next major of Wallabag app.

If you want to join the beta, you can [follow the Testflight link](https://testflight.apple.com/join/RF9hzKHt). Keep in mind the beta still is unstable, and any update can completely break the app (and potentially do some nasty things on your Wallabag instance).

This issue will be closed when Wallabag 5.0.0 will be released. Feel free to re-open it if the problem still occurs.

**Closed** 2020-03-02 12:24 UTC
Labels: Bug, Fixed in v5
