### ISSUE TITLE
Improve usability of register/login

### ISSUE THREAD

**Issue by baurmatt** [wallabag/ios-app#132] opened 2017-12-13 21:30 UTC
| Q             | A
| ------------- | ---
| Device?       | iPhone
| Device Os version    | 11.1.2
| App Version   | 2.3
| Wallabag server version | 2.3

### Steps to reproduce/test case

- Download the app
- Open the app
- Go back to your Wallabag instance in order to create a Client ID and secret
- Go back to iOS/iPhone
- Enter ~50 characters of a Client ID (on a mobile device!)
- Enter ~50 characters of a Client secret (on a mobile device!)
- Enter your username
- Enter your password
- Finally logged in (if everything was correct)

### Improvement
Please improve the register/login process for the client. Currently the usability is completely broken.

**Comment by bourvill** [comment] 2017-12-14 08:48
Hello, thanks for your feedback.
You right, the login process are clearly unusable. And we need to focus on it.
Actually many instance exist, and each user have different instance (url, client_id, client_secret), the problem is here.
We need to update the wallabag server before the ios-app

**Comment by jobspierings** [comment] 2019-09-09 09:16
As an intermediate fix for this issue perhaps the following could help: add some text and links on the first screens of Wallabag iOS app. Specifically:

- When you don't have your own server, the URL to be entered is (most likely): https://app.wallabag.it
- provide a direct link to https://app.wallabag.it/developer/client/create 
 
context: I spend quite some time puzzling what the correct URL should be (e.g. `api.wallabag.it` or  `api.wallabag.or` or `wallabag.it`). As far as I can see it is not explicitly listed anywhere.

**Comment by bourvill** [comment] 2019-09-09 09:19
Thanks @jobspierings for your feedback, they will be taken for the next major version of the application

**Comment by thibaultamartin** [comment] 2020-02-21 08:30
I'm closing this issue as a duplicate of the more recent #244, which references discussion for this on the server-side. You can follow issue #244 to keep track of progress.

**Closed by thibaultamartin** 2020-02-21 08:30 UTC
