### ISSUE TITLE
Unable to select article during sync refresh

### ISSUE THREAD

**Issue by burkemw3** [wallabag/ios-app#198] opened 2019-06-25 04:27 UTC
| Q             | A
| ------------- | ---
| Device?       | iPhone
| Device Os version    | 12.3.1
| App Version   | 4.1.0 219
| Wallabag server version | 2.3.8

### Steps to reproduce/test case

0. Sync articles (pull down on article list page)
0. While sync is in progress, select an article

Expected: article opens
Actual: article list flashes repeatedly

Can only select articles when sync progress bar is nearly or fully finished. This is especially annoying on first open, as sync is immediately triggered on open.

### Improvement

Sync in background; allow UI usage during sync

**Comment by thibaultamartin** [comment] 2020-02-21 08:13
Hello,

The Wallabag app is being rewritten. I cannot reproduce it in the build 242 of Wallabag 5.0.0 Beta, meaning your issue is most likely fixed in the next major of Wallabag app.

If you want to join the beta, you can [follow the Testflight link](https://testflight.apple.com/join/RF9hzKHt). Keep in mind the beta still is unstable, and any update can completely break the app (and potentially do some nasty things on your Wallabag instance).

This issue will be closed when Wallabag 5.0.0 will be released. Feel free to re-open it if the problem still occurs.

**Closed** 2020-03-02 12:24 UTC
Labels: Bug, Fixed in v5
