### ISSUE TITLE
Configure swipe article

### ISSUE THREAD

**Issue by bourvill** [wallabag/ios-app#50] opened 2016-12-08 11:25 UTC
Ref #36 suggest 

Maybe make them configurable will be nice to:
- configure the swipe on the right
- configure the swipe on the left

With these options:
- delete article
- mark as read / unread
- star / unstar

**Comment by thibaultamartin** [comment] 2020-02-21 08:40
Closing as duplicate of #243

**Closed by thibaultamartin** 2020-02-21 08:40 UTC
