### ISSUE TITLE
Adding an already saved page fails silently

### ISSUE THREAD

**Issue by notquitehere** [wallabag/ios-app#222] opened 2019-10-17 07:00 UTC
When attempting to add a page which is already in your list there is no feedback to let you know that it already exists leaving the user wondering if the save has failed.

Potential solution:

either

- have the item appear at the top of the list
- have a prompt flash up letting the user know their item is already in the list.

| ------------- | ---
| Device?       | iPhone/iPad
| Device Os version    | 9.0/10.0
| App Version   | 2.0
| Wallabag server version | 2.0

**Comment by bourvill** [comment] 2019-10-17 08:16
Hi ,
It's from share extension or directly in app?

**Comment by gingerlime** [comment] 2019-11-16 13:31
I’m having trouble adding items in general. Some are added without issues others just silently fail. Tried both via share item, copy (it prompts me to add it), and pasting with the plus icon. It just seem to fail silently and I can’t see the item. Searching for keywords in the article return zero results... there’s also an unrelated(?) bug for me that after searching and not finding anything all articles are gone. I have to force quit the app. On iPhone 5s iOS 12.4.2

**Comment by bourvill** [comment] 2019-11-18 09:04
can you share an example of an url on which you had a problem?

**Comment by gingerlime** [comment] 2019-11-18 12:06
I bumped into a couple but I think this one is the one I tried via different means and all failed (later it was added just fine via the desktop browser extension)

https://www.brainpickings.org/2014/03/28/daniel-dennett-rapoport-rules-criticism/

**Comment by notquitehere** [comment] 2019-12-02 12:06
> Hi ,
> It's from share extension or directly in app?

Both, if the link is already there the app appears to do nothing rather than telling you that you've already saved it.

**Comment by thibaultamartin** [comment] 2020-02-21 08:07
Hello,

The Wallabag app is being rewritten. I cannot reproduce it in the build 242 of Wallabag 5.0.0 Beta, meaning your issue is most likely fixed in the next major of Wallabag app.

If you want to join the beta, you can [follow the Testflight link](https://testflight.apple.com/join/RF9hzKHt). Keep in mind the beta still is unstable, and any update can completely break the app (and potentially do some nasty things on your Wallabag instance).

This issue will be closed when Wallabag 5.0.0 will be released. Feel free to re-open it if the problem still occurs.

**Closed** 2020-03-02 12:24 UTC
Labels: Bug, Fixed in v5
